### ISSUE TITLE
Packages in Haxe

### ISSUE THREAD

**Issue by markknol** [altef/logipar#1]
Just stumbled on this library and noticed small thing that can be improved:
https://github.com/altef/logipar/blob/master/src/logipar/Node.hx#L1-L4
You can rewrite the package/name with `@:expose("Node")` (or `@:expose("long.package.path.Node")` if you ever want something like that). Then you uses normal packages without hacks (and remove all the `#if` stuff), but with `@:expose("Node")` it will export as if is was in top level package.

**Comment by altef** [comment]
Hey thanks!  As far as I can tell expose seems to only apply to Javascript, though I'm admittedly foggy on that portion (and others) of the Haxe docs.  I ran some tests just now though, and they *seem* to verify that.

Basically doing `@expose("Node")` would expose it as `Node` for javascript, and `namespace logipar;` for PHP, which is ideal.  

The problem is with python.  If the `package` line is present, it names the class `logipar_Node`.  Honestly, that's fine for `Node`, but it seems overly wordy in situations like:

```python
import logipar

l = logipar.logipar_Logipar() # so many logipars
```

Which is why I included the `#if` stuff.

However, it may be worth it to simplify the `#if` portion to only account for python, and handle the javascript bit through `@expose(...)`.  What are your thoughts on that?

**Comment by markknol** [comment]
Can you try `@:native("Node")` too?

**Comment by altef** [comment]
Interesting! I got it working on my local using
```haxe
@:native(...)
@:expose(...)
```


`@:native` seems to do all the things I want. 
* It renames for Javascript  and python as `Node` 
* ~php is still under the `namespace logipar;` (Hopefully this is intended behaviour, rather than a bug to be fixed)~

I'm not exactly sure what it does for *other* targets.  But it seems to work for these.  I won't have as fine-grained control should I add `c#` or `java`, or the like.  But worst-case I can always switch back to the `#if` method.  (Or potentially `#if` in a different `@:native(...)` depending on target?)



*Edit*: Nevermind, I was wrong about PHP.  I was looking at an old file.  It does strip out the namespace.  I guess i'd either have to do:
```haxe
#if !php
@:native('Node')
#end
```
or stick with what I have

**Comment by altef** [comment]
Updated to:
```haxe
package logipar;

#if !php
@:native('Node')
@:expose('Node')
#end
```
